# Generated by Django 5.2.5 on 2025-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('background', models.ImageField(blank=True, null=True, upload_to='thumbnails/backgrounds/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='thumbnails/logos/')),
                ('output', models.ImageField(blank=True, null=True, upload_to='thumbnails/generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
