# Generated by Django 5.2.5 on 2025-09-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=512)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='youtube_uploads/videos/')),
                ('video_path', models.CharField(blank=True, help_text='Path on server (if not uploading file)', max_length=500, null=True)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True)),
                ('caption_path', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=32, null=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
